server:
  port: 80

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, prometheus

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
