version: '1.0'
services:
  api:
    image: gold-mining-api
    container_name: compose-api
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    container_name: compose-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana
    container_name: compose-grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus
  client:
    image: gold-mining-client
    container_name: compose-client
    depends_on:
      - api
