global:
  scrape_interval: "2s"
  evaluation_interval: "2s"
scrape_configs:
  - job_name: "springboot"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8080"
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
